root: true

env:
    browser: true
    commonjs: true
    es2021: true
    node: true
    es2017: true
    jest: true
plugins:
    - '@typescript-eslint'
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - standard
    - standard-with-typescript
    - prettier
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: ./tsconfig.eslint.json
rules:
    react/jsx-uses-react: 'off'
    react/react-in-jsx-scope: 'off'
